- hosts: all
  become: yes
  vars:
    docker_virtualenv_path: "/home/{{ ansible_user }}/docker-venv"
    internal_web_app_port: "5000"
  tasks:
    - name: Enable EPEL repo
      yum:
        name: epel-release
        state: installed
      tags:
        - common
    - name: Install yum utils
      yum:
        name: yum-utils
        state: installed
      tags:
        - common
    - name: Install PIP
      yum:
        name: python3-pip
        state: installed
      tags:
        - common
    - name: Upgrade pip
      pip:
        name: pip
        version: "21.3.1"
      tags:
        - common
    - name: Install Virtualenv
      pip:
        name: virtualenv
        version: "20.10.0"
      tags:
        - common      
    - name: Install Docker
      block:
        - name: Add Docker repository
          command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          args:
            creates: /etc/yum.repos.d/docker-ce.repo
        - name: Install Docker
          yum:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: installed
      tags:
        - docker
    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
      tags:
        - docker
    - name: Install Shibboleth service provider
      block:
        - name: Add Shibboleth repository
          yum_repository:
            name: shibboleth
            description: Shibboleth (CentOS_8)
            gpgcheck: no
            gpgkey: https://download.opensuse.org/repositories/security:/shibboleth/CentOS_8/repodata/repomd.xml.key
            mirrorlist: https://shibboleth.net/cgi-bin/mirrorlist.cgi/CentOS_8
        - name: Install Shibboleth package
          yum:
            name: shibboleth.x86_64
            state: installed
      tags:
        - shibboleth
    - name: Install Apache HTTPD server
      yum:
        name:
          - httpd.x86_64
          - mod_ssl
        state: installed
      tags:
        - apache
    - name: Configure Shibboleth service provider
      block:
        - name: Check if Shibboleth keys and certificates exist locally
          local_action: command stat {{ inventory_dir }}/shibboleth-crypto/{{ item }}
          become: no
          failed_when: no
          changed_when: false
          loop:
            - sp-encrypt-cert.pem
            - sp-encrypt-key.pem
            - sp-signing-cert.pem
            - sp-signing-key.pem
          register: shib_keys_and_certificates_stats
        - name: Copy Shibboleth keys and certificates
          copy:
            src: "{{ inventory_dir }}/shibboleth-crypto/{{ item }}"
            dest: /etc/shibboleth
            mode: "0644"
          with_items:
            - sp-encrypt-cert.pem
            - sp-encrypt-key.pem
            - sp-signing-cert.pem
            - sp-signing-key.pem
          when: (shib_keys_and_certificates_stats.results | selectattr('rc') | list | length) == 0
        - name: Copy Shibboleth attribute map
          copy:
            src: files/etc/shibboleth/attribute-map.xml
            dest: /etc/shibboleth
            mode: "0644"
        - name: Download Identity Provider's metadata
          get_url:
            url: "{{ saml_identity_provider_metadata_url }}"
            dest: /etc/shibboleth/idp-metadata.xml
            mode: "0644"
        - name: Create Shibboleth main configuration file
          template:
            src: files/etc/shibboleth/shibboleth2.xml.j2
            dest: /etc/shibboleth/shibboleth2.xml
            mode: "0644"
        - name: Start Shibboleth service
          systemd:
            name: shibd
            state: started
            enabled: yes
      tags:
        - shibboleth
    - name: Configure Apache HTTPD server
      block:
        - name: Remove Apache welcome.conf configuration file
          file:
            path: /etc/httpd/conf.d/welcome.conf
            state: absent
        - name: Create the main Apache configuration file
          template:
            src: files/etc/httpd/conf/httpd.conf.j2
            dest: /etc/httpd/conf/httpd.conf
            mode: "0644"
        - name: Create the Shibboleth Apache configuration file
          template:
            src: files/etc/httpd/conf.d/shib.conf.j2
            dest: /etc/httpd/conf.d/shib.conf
            mode: "0644"
              #        - name: Set httpd_can_network_connect flag on
              #          seboolean:
              #            name: httpd_can_network_connect
              #            state: yes
              #            persistent: yes
        - name: Start Apache service
          systemd:
            name: httpd
            state: started
            enabled: yes
      tags:
        - apache
    - name: Prepare the bind mounts for the MC Hub container
      block:
        - name: Create the MC Hub work directory
          file:
            path: "/home/{{ ansible_user }}/mcui"
            state: directory
        - name: Copy the OpenStack configuration file
          copy:
            src: "{{ inventory_dir }}/clouds.yaml"
            dest: "/home/{{ ansible_user }}/mcui"
        - name: Copy the Google Cloud service account configuration file
          copy:
            src: "{{ inventory_dir }}/gcloud-key.json"
            dest: "/home/{{ ansible_user }}/mcui"
        - name: Copy the MC Hub configuration file
          copy:
            src: "{{ inventory_dir }}/configuration.json"
            dest: "/home/{{ ansible_user }}/mcui"
        - name: Create the clusters backup directory
          file:
            path: "/home/{{ ansible_user }}/mcui/clusters_backup"
            state: directory
            mode: "0777"
      tags:
        - docker
    - name: Install Docker SDK for Python
      # docker_container module requires Docker SDK for Python
      block:
        - name: Create Docker SDK for Python's virtual environment
          command:
            cmd: /usr/local/bin/virtualenv {{ docker_virtualenv_path }}
            creates: "{{ docker_virtualenv_path }}"
        - name: Install Docker SDK for Python
          pip:
            name: docker
            version: "4.3.0"
            virtualenv: "{{ docker_virtualenv_path }}"
      tags:
        - docker
    - name: Start the MC Hub container
      vars:
        ansible_python_interpreter: "{{ docker_virtualenv_path }}/bin/python"
      docker_container:
        name: mcui
        image: fredericfc/magic_castle-ui:{{ mc_hub_version }}
        restart_policy: always
        state: started
        env:
          OS_CLOUD: "{{ default_cloud  }}"
        published_ports:
          - "{{ internal_web_app_port }}:5000"
        mounts:
          - source: database
            target: /home/mcu/database
            type: volume
          - source: "/home/{{ ansible_user }}/mcui/gcloud-key.json"
            target: /home/mcu/credentials/gcloud-key.json
            type: bind
          - source: "/home/{{ ansible_user }}/mcui/clouds.yaml"
            target: /home/mcu/.config/openstack/clouds.yaml
            type: bind
          - source: "/home/{{ ansible_user }}/mcui/clusters_backup"
            target: /home/mcu/clusters
            type: bind
          - source: "/home/{{ ansible_user }}/mcui/configuration.json"
            target: /home/mcu/configuration.json
            type: bind
          - source: "/home/{{ ansible_user }}/mc-hub/app"
            target: /home/mcu/app
            type: bind
      tags:
        - docker
    - name: Enable HTTPS
      # Inspired by https://certbot.eff.org/lets-encrypt/centosrhel7-apache
      block:
        - name: Install Certbot
          yum:
            name:
              - certbot
              - python3-certbot-apache
            state: installed
        - name: Check whether HTTPS keys and certificates already exist
          stat:
            path: "{{ item }}"
          loop:
            - /etc/letsencrypt/live/{{ fqdn }}/cert.pem
            - /etc/letsencrypt/live/{{ fqdn }}/privkey.pem
            - /etc/letsencrypt/live/{{ fqdn }}/chain.pem
            - /etc/letsencrypt/live/{{ fqdn }}/fullchain.pem
          register: https_keys_and_certificates_stats
        - name: Generate HTTPS certificate
          # Only generate HTTPS keys and certificate when they don't already exist
          when: https_keys_and_certificates_stats.results | rejectattr('stat.exists') | list
          command:
            cmd: certbot -n --apache -d {{ fqdn }} -m {{ server_admin_email }} --agree-tos certonly
        - name: Create the HTTPS Apache configuration file
          template:
            src: files/etc/httpd/conf.d/httpd-le-ssl.conf.j2
            dest: /etc/httpd/conf.d/httpd-le-ssl.conf
            mode: "0644"
        - name: Setup automatic HTTPS certificate renewal 
          cron:
            name: Let's Encrypt HTTPS certificate renewal
            cron_file: /etc/crontab
            minute: "0"
            hour: "0,12"
            day: "*"
            month: "*"
            weekday: "*"
            user: root
            job: "python -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot renew -q"
      tags:
        - apache
          #    - name: Configure Filebeat
          #      block:
          #        - name: Create downloads directory
          #          file:
          #            path: "/home/{{ ansible_user }}/Downloads"
          #            state: directory
          #        - name: Download Filebeat
          #          get_url:
          #            url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.0.1-x86_64.rpm
          #            dest: "/home/{{ ansible_user }}/Downloads/filebeat.rpm"
          #        - name: Install Filebeat
          #          yum:
          #            name: "/home/{{ ansible_user }}/Downloads/filebeat.rpm"
          #            state: present
          #        - name: Configure Filebeat
          #          template:
          #            src: files/etc/filebeat/filebeat.yml
          #            dest: /etc/filebeat/filebeat.yml
          #            mode: "0644"
          #        - name: Copy logstash certificate
          #          copy:
          #            src: "{{ inventory_dir }}/logstash-servers.crt"
          #            dest: /etc/filebeat/logstash-servers.crt
          #        - name: Start Filebeat service
          #          systemd:
          #            name: filebeat
          #            state: started
          #            enabled: yes
          #      tags:
          #        - filebeat
